In [1]:
a=2
b=4
c=a+b
print(c)

6


In [2]:
a=int(input("Enter a:"));
b=int(input("Enter b:"));
c=int(input("Enter c:"));
if (a>b and a>c):
    print("Hello, Ans is a:",a)
elif (b>c and b>a):
    print("Hello, Ans is b:",b)
else:
    print("Hello, Ans is c:",c)

ValueError: invalid literal for int() with base 10: ''

In [3]:
num=int(input("enter number"))
if num%2==0:
    if num%3==0:
        print ("Divisible by 3 and 2")
    else:
        print ("divisible by 2 not divisible by 3")
else:
    if num%3==0:
        print ("divisible by 3 not divisible by 2")
    else:
        print ("not Divisible by 2 not divisible by 3")


divisible by 2 not divisible by 3


In [4]:
for letter in 'Hello World!':
    print('current letter:',letter)

current letter: H
current letter: e
current letter: l
current letter: l
current letter: o
current letter:  
current letter: W
current letter: o
current letter: r
current letter: l
current letter: d
current letter: !


In [5]:
fruits = ['banana', 'apple', 'mango']
for fruit in fruits: 
    print ('Current fruit :', fruit)

Current fruit : banana
Current fruit : apple
Current fruit : mango


In [6]:
fruits = ['banana', 'apple', 'mango',12345]
for fruit in fruits: 
    print ('Current fruit :', fruit)

print(" ")
for index in range(len(fruits)):
    print('current fruit:',fruits[index])

Current fruit : banana
Current fruit : apple
Current fruit : mango
Current fruit : 12345
 
current fruit: banana
current fruit: apple
current fruit: mango
current fruit: 12345


In [17]:
numbers=[11,33,21,55,39,66,75,37,21,23,41,13]

for num in numbers:
    if num%2==0:
        
        print(num,"is even")
        break
    else:
        print(num,'odd')
        


11 odd
33 odd
21 odd
55 odd
39 odd
66 is even


In [18]:
num=[11,33,22,55,39,55,75,37,37,21,23,41,21,9,21]
a=len(num)
b=max(num)
print("maximum is:",b,"    ")
num.append(90)
b=max(num)
c=min(num)
print('length:',a,'maximum:',b,'minimum:',c)
i=int(input('enter value to be checked:'))
print('how many times the number occured',num.count(i))
num.reverse()

print('after reversing:',num)

maximum is: 75     
length: 15 maximum: 90 minimum: 9
how many times the number occured 0
after reversing: [90, 21, 9, 21, 41, 23, 21, 37, 37, 75, 55, 39, 55, 22, 33, 11]


In [ ]:
str="jigar"
a=str.upper()
b=str.isupper()
c=len(str)
d=str.lower()
f=max(str)
e=min(str)
print('converts all char to uppercase:',a)
print("its boolean f^n to check its first char is upper or not:",b)
print('gives length of string:',c)
print('lowers all char:',d)
print('gives max char(ascii):',f)
print('gives minimum ascii char:',e)

converts all char to uppercase: JIGAR
its boolean f^n to check its first char is upper or not: False
gives length of string: 5
lowers all char: jigar
gives max char(ascii): r
gives minimum ascii char: a


In [ ]:
#pass by value into function::::
def change(list):
    print("values inside the function before change:",list)
    list[2]="Jigar"
    print("after change:",list)
    return 0

list=[10,20,30,40,'Hello']
change(list)
print("values outside function:",list)
    


values inside the function before change: [10, 20, 30, 40, 'Hello']
after change: [10, 20, 'Jigar', 40, 'Hello']
values outside function: [10, 20, 'Jigar', 40, 'Hello']


In [ ]:
# pass by reference(i think!)
def change(list):
    list=[10,20,30,40,'Hello']
    print("values inside function:",list)
    return 0

list=[10,2,35,52,'jigar','hello']
change(list)
print("values after change",list)

values inside function: [10, 20, 30, 40, 'Hello']
values after change [10, 2, 35, 52, 'jigar', 'hello']


In [ ]:
total=0
def sum(a,b):
    total=a+b;
    print('inside the function is local total:',total)
    return total
x=int(input("enter a:"))
print("x is:",x)
y=int(input("Enter b:"))
print("y is:",y)
sum(x,y)
print("Outside the function the global variable total is:",total)

x is: 2
y is: 2
inside the function is local total: 4
Outside the function the global variable total is: 0


In [ ]:
import numpy as np

arr=np.array([ [1,2,3,4,5],
               [12,13,14,15,20] ], )

print("array is of type:",type(arr))
print("No. of dimensions:",arr.ndim)
print("Shape of array:",arr.shape)
print(arr)
print("size of array:",arr.size)

ModuleNotFoundError: No module named 'numpy'

In [ ]:
arr=np.array([ [1,2,3,4,0],
               [0,13,14,15,20] ],bool )
print(arr)
print("")
arr=np.array([ [1,2,3,4,5],
               [12,13,14,15,20] ], float)
print(arr)
print('')
arr=np.array([ [1,2,3,4,5],
               [12,13,14,15,20] ], int)
print(arr)
print("")
arr=np.array([ [1,2,3,4,5],
               [12,13,14,15,20] ], complex)
print(arr)

[[ True  True  True  True False]
 [False  True  True  True  True]]

[[ 1.  2.  3.  4.  5.]
 [12. 13. 14. 15. 20.]]

[[ 1  2  3  4  5]
 [12 13 14 15 20]]

[[ 1.+0.j  2.+0.j  3.+0.j  4.+0.j  5.+0.j]
 [12.+0.j 13.+0.j 14.+0.j 15.+0.j 20.+0.j]]


In [ ]:
import numpy as np

a=np.array([[1, 2, 4], [5, 8, 7]],float)
print("\n",a)

b = np.array((1 , 3, 2))
print("\n",b)

c=np.zeros((3,4))
print("\n",c)

d=np.ones((2,3))
print("\n",d)

e=np.random.random((2,2))
print("\n",e)

f=np.arange(0,50,10)
print("creates a sequence of integers, from 0 to 50 with step 10\n",f)

arr = np.array([[1, 2, 3, 4],
                [5, 2, 4, 2],
                [1, 2, 0, 1]])
 
newarr = arr.reshape(2, 2, 3)
 
print ("Original array:\n", arr)
print ("Reshaped array:\n", newarr)


 [[1. 2. 4.]
 [5. 8. 7.]]

 [1 3 2]

 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 [[1. 1. 1.]
 [1. 1. 1.]]

 [[0.87924051 0.55769544]
 [0.69967417 0.62387872]]
creates a sequence of integers, from 0 to 50 with step 10
 [ 0 10 20 30 40]
Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array:
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]


In [ ]:
arr = np.array([[1, 2, 3, 4],
                [5, 2, 4, 2],
                [1, 2, 0, 1]])
 
newarr = arr.reshape(2, 2, 3)
 
print ("\nOriginal array:\n", arr)
print ("Reshaped array:\n", newarr)


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array:
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]


In [ ]:
import numpy as np

n=int(input("Enter number"))
mylist=[]
for i in range(n):
    x=int(int(input("Enter value of:")))
    mylist.append(x)

# print(mylist)

arr=np.array(mylist)
print(arr)

mean=np.mean(arr)
print(mean)

var=np.var(arr)
print(var)

stddev=np.std(arr)
print(stddev)

median=np.median(arr)
print(median)
# _________________________________________________________________________________________________ #

import statistics as st
mode=st.mode(arr)
print(mode)

sum=0
for i in range(n):
    sum=sum+arr[i]
avg=sum/n
print(avg)




Enter number5
Enter value of:12
Enter value of:10
Enter value of:5
Enter value of:2
Enter value of:3
[12 10  5  2  3]
6.4
15.440000000000001
3.9293765408777004
5.0
12
6.4


In [ ]:
import numpy as np

a=np.array([1,2,3,4,5,7,6,8,9,3],int)
for i in a:
    print(i+10)
sum=np.sum(a)
print('The sum of all numbers is',sum)
np.save('numpy',sum)

x=np.arange(10)
y=np.random.randint(1,10,(2,3))
np.savez('numpy1',first=x,second=y)
np.load('numpy1.npz')
print(x,y)




11
12
13
14
15
17
16
18
19
13
The sum of all numbers is 48
[0 1 2 3 4 5 6 7 8 9] [[7 7 3]
 [1 3 2]]
