In [1]:
import pandas as pd
import numpy as np
import time
from itertools import permutations

data=pd.read_csv('11citytsp.csv',header=None).values
print(data)
print(data.dtype)
citynames=list(range(data.shape[0]))
print(citynames)
pm=permutations(citynames)

st=time.process_time()
best_tour_length=np.inf
for tour in pm:
    tour_length=0
    for i in range(len(tour)-1):
        tour_length+=data[tour[i],tour[i+1]]
    tour_length+=data[tour[i+1],tour[0]]
    
    if tour_length < best_tour_length:
        best_tour_length=tour_length
        best_tour=tour
et=time.process_time()
time_taken=(et-st)*1000
print("Best tour",best_tour)
print("Best tour length",best_tour_length)
print("Time Taken:",time_taken)

[[  0 633 257  91 412 150  80 134 259 505 353]
 [633   0 390 661 227 488 572 530 555 289 282]
 [257 390   0 228 169 112 196 154 372 262 110]
 [ 91 661 228   0 383 120  77 105 175 476 324]
 [412 227 169 383   0 267 351 309 338 196  61]
 [150 488 112 120 267   0  63  34 264 360 208]
 [ 80 572 196  77 351  63   0  29 232 444 292]
 [134 530 154 105 309  34  29   0 249 402 250]
 [259 555 372 175 338 264 232 249   0 495 352]
 [505 289 262 476 196 360 444 402 495   0 154]
 [353 282 110 324  61 208 292 250 352 154   0]]
int64
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Best tour (0, 3, 8, 4, 1, 9, 10, 2, 5, 7, 6)
Best tour length 1639
Time Taken: 348515.625


In [2]:
import pandas as pd
from itertools import permutations
import numpy as np
import time
mat=pd.read_csv('11citytsp.csv',header=None).values
citynames=list(range(mat.shape[0]))
startcity=int(input("Enter starting city from 0 to 11:"))
citynames.remove(startcity)
per=permutations(citynames)


st=time.process_time()
besttourlength=np.inf
for tour in per:
    tourlength=0
    for i in range(len(tour)-1):
        tourlength+=mat[tour[i],tour[i+1]]
    tourlength+=mat[tour[i+1],startcity]
    tourlength+=mat[startcity,tour[0]]
    
    if tourlength < besttourlength:
        besttourlength=tourlength
        besttour=tour
et=time.process_time()
time_taken=(et-st)*1000
print("Best tour",besttour)
print("Best tour length",besttourlength)
print("Time Taken:",time_taken)

Enter starting city from 0 to 11:5
Best tour (2, 10, 9, 1, 4, 8, 3, 0, 6, 7)
Best tour length 1639
Time Taken: 30625.0
